### ISSUE TITLE
Unknown DB type: timestamp without time zone [PostgresQL]

### ISSUE THREAD

**Issue by tansautn** [nova-horizons/realoquent#163]
### Realoquent Version

0.6.0

### Laravel Version

11.27.2

### PHP Version

8.2.24

### Operating System & Version

Debian 11

### Database Type & Version

Postgres 16.4 (Debian 16.4-1.pgdg110+2)

### Description

Step in setup schema then i got bellow exception:

```
[2024-10-13 20:27:35] development.ERROR: Unknown DB type: timestamp without time zone {"exception":"[object] (RuntimeException(code: 0): Unknown DB type: timestamp without time zone at /var/_www/fitly/vendor/nova-horizons/realoquent/src/TypeDetector.php:115)
[stacktrace]
#0 /var/_www/fitly/vendor/nova-horizons/realoquent/src/TypeDetector.php(22): NovaHorizons\\Realoquent\\TypeDetector::fromPostgreSQL()
#1 /var/_www/fitly/vendor/nova-horizons/realoquent/src/DatabaseAnalyzer.php(28): NovaHorizons\\Realoquent\\TypeDetector::fromDB()
#2 /var/_www/fitly/vendor/nova-horizons/realoquent/src/DataObjects/Table.php(262): NovaHorizons\\Realoquent\\DatabaseAnalyzer::getColumns()
#3 /var/_www/fitly/vendor/nova-horizons/realoquent/src/SchemaManager.php(28): NovaHorizons\\Realoquent\\DataObjects\\Table::fromDB()
#4 /var/_www/fitly/vendor/nova-horizons/realoquent/src/RealoquentManager.php(84): NovaHorizons\\Realoquent\\SchemaManager->rebuildSchema()
#5 /var/_www/fitly/vendor/nova-horizons/realoquent/src/RealoquentManager.php(75): NovaHorizons\\Realoquent\\RealoquentManager->generateSchema()
#6 /var/_www/fitly/vendor/nova-horizons/realoquent/src/Commands/GenerateSchema.php(36): NovaHorizons\\Realoquent\\RealoquentManager->generateAndWriteSchema()
#7 /var/_www/fitly/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): NovaHorizons\\Realoquent\\Commands\\GenerateSchema->handle()
#8 /var/_www/fitly/vendor/laravel/framework/src/Illuminate/Container/Util.php(43): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#9 /var/_www/fitly/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(95): Illuminate\\Container\\Util::unwrapIfClosure()
#10 /var/_www/fitly/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(35): Illuminate\\Container\\BoundMethod::callBoundMethod()
#11 /var/_www/fitly/vendor/laravel/framework/src/Illuminate/Container/Container.php(690): Illuminate\\Container\\BoundMethod::call()
#12 /var/_www/fitly/vendor/laravel/framework/src/Illuminate/Console/Command.php(213): Illuminate\\Container\\Container->call()
#13 /var/_www/fitly/vendor/symfony/console/Command/Command.php(279): Illuminate\\Console\\Command->execute()
#14 /var/_www/fitly/vendor/laravel/framework/src/Illuminate/Console/Command.php(182): Symfony\\Component\\Console\\Command\\Command->run()
#15 /var/_www/fitly/vendor/symfony/console/Application.php(1047): Illuminate\\Console\\Command->run()
#16 /var/_www/fitly/vendor/symfony/console/Application.php(316): Symfony\\Component\\Console\\Application->doRunCommand()
#17 /var/_www/fitly/vendor/symfony/console/Application.php(167): Symfony\\Component\\Console\\Application->doRun()
#18 /var/_www/fitly/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(197): Symfony\\Component\\Console\\Application->run()
#19 /var/_www/fitly/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(1203): Illuminate\\Foundation\\Console\\Kernel->handle()
#20 /var/_www/fitly/artisan(13): Illuminate\\Foundation\\Application->handleCommand()
#21 {main}
```

here is one of my table have timestamp column that existing on DB.

```
CREATE TABLE accounts (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    site_id BIGINT NOT NULL, -- Liên kết với bảng bet_sites
    username VARCHAR(255) NOT NULL,
    pwd VARCHAR(255) NOT NULL, 
    email VARCHAR(255),
    phone VARCHAR(50),
    reg_at TIMESTAMP,
    last_login_at TIMESTAMP, -- Thời gian đăng nhập lần cuối
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, 
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (site_id) REFERENCES bet_sites(id)
);
CREATE INDEX idx_accounts_site_id ON accounts(site_id);
CREATE INDEX idx_accounts_username ON accounts(username);
CREATE INDEX idx_accounts_email ON accounts(email);
CREATE INDEX idx_accounts_phone ON accounts(phone);
```

**Comment by pb30** [comment]
Apologies for the delay, just published v0.7.0. Let me know if that resolves the issue. I haven't done much real-word testing with Postgres yet, so let me know if any other problems pop up, or any other thoughts you have about this library.

**Comment by tansautn** [comment]
Hello.

I were tested with version 0.7.0 and still occured the error.

Do you need more dump, please let me know.

Here is console commands & output:
```
web@zuko:/www/fitly$ composer8.2 req nova-horizons/realoquent --dev
./composer.json has been updated
Running composer update nova-horizons/realoquent
Loading composer repositories with package information
Updating dependencies
Lock file operations: 0 installs, 1 update, 0 removals
  - Upgrading nova-horizons/realoquent (v0.6.0 => v0.7.0)
Writing lock file
Installing dependencies from lock file (including require-dev)
Package operations: 0 installs, 1 update, 0 removals
  - Downloading nova-horizons/realoquent (v0.7.0)
  - Upgrading nova-horizons/realoquent (v0.6.0 => v0.7.0): Extracting archive
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi

   INFO  Discovering packages.

  barryvdh/laravel-debugbar ................................................................................................................... DONE
  irazasyed/telegram-bot-sdk .................................................................................................................. DONE
  laravel/sail ................................................................................................................................ DONE
  laravel/sanctum ............................................................................................................................. DONE
  laravel/tinker .............................................................................................................................. DONE
  nesbot/carbon ............................................................................................................................... DONE
  nova-horizons/realoquent .................................................................................................................... DONE
  nunomaduro/collision ........................................................................................................................ DONE
  nunomaduro/termwind ......................................................................................................................... DONE
  spatie/laravel-ignition ..................................................................................................................... DONE

85 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
> @php artisan vendor:publish --tag=laravel-assets --ansi --force

   INFO  No publishable resources for tag [laravel-assets].

No security vulnerability advisories found
Using version ^0.7.0 for nova-horizons/realoquent
web@zuko:/www/fitly$ php8.2 artisan realoquent:generate-schema

   RuntimeException

  Unknown DB type: timestamp without time zone

  at vendor/nova-horizons/realoquent/src/TypeDetector.php:120
    116▕             'time(0) without time zone' => ColumnType::time,
    117▕             'timestamp(0) without time zone' => ColumnType::timestamp,
    118▕             'timestamp(0) with time zone' => ColumnType::timestampTz,
    119▕             'uuid' => ColumnType::uuid,
  ➜ 120▕             default => throw new RuntimeException('Unknown DB type: '.$type),
    121▕         };
    122▕     }
    123▕
    124▕     private static function fromSqlite(mixed $type): ColumnType

      +20 vendor frames

  21  artisan:13
      Illuminate\Foundation\Application::handleCommand()

web@zuko:/www/fitly$
```

**Comment by tansautn** [comment]
i see in your pull request: There some types were added, but not mine. I know it will need more tests. But just leave it here. In case you need it.
`timestamp without time zone` is $type (string)

**Comment by pb30** [comment]
Doh, released 0.7.1 with the additional type, not quite sure at the moment why there's subtle differences in the returned types compared to tests, but will look into it more.

**Comment by tansautn** [comment]
It's seem setup process passed.

Then there's a "warning".

Since i have mutilple php version on my server. Then Main command class of realoquent will failed if i does not set active version = requirement of realoquent. (I used `update-alternatives` to manage symlink of `/usr/bin/php`)

Env setup : primary PHP : 7.4
command was ran by using php8.2.

See console log bellow
```
web@zuko:/www/fitly$ php8.2 artisan realoquent:generate-schema
Realoquent Schema file generated successfully: /var/_www/fitly/database/realoquent/schema.php

   RuntimeException

  Failed to run code style fixer. Check `cs_fixer_command` config value.
Box Requirements Checker
========================

> Using PHP 7.4.33
> PHP is using the following php.ini file:
  /etc/php/7.4/cli/php.ini

> Checking Box requirements:
  E.....


 [ERROR] Your system is not ready to run the application.


Fix the following mandatory requirements:
=========================================

 * The application requires a version matching "^8.1.0".

  at vendor/nova-horizons/realoquent/src/RealoquentManager.php:136
    132▕         }
    133▕
    134▕         foreach ($commands as $command) {
    135▕             $result = Process::path(base_path())->run($command);
  ➜ 136▕             throw_unless($result->successful(), new \RuntimeException('Failed to run code style fixer. Check `cs_fixer_command` config value. '.$result->errorOutput()));
    137▕
    138▕         }
    139▕     }
    140▕

      +14 vendor frames

  15  artisan:13
      Illuminate\Foundation\Application::handleCommand()
```

I did not read the code yet, but rely on `php` in PATH is not really good pratice

**Comment by pb30** [comment]
You can adjust your config by updating the `cs_fixer_command` value to use the proper version of PHP on your system. By default it is using `./vendor/bin/pint {file}`, but you can prefix that with the correct PHP path.

**Comment by tansautn** [comment]
From now please let me use "our package" to ref to `realoquent`
I known that there a configuration var for that. But i just want more powerful to the package. See bellow

#### Background
Currently, when running commands like pint through our package, it may use the system's default PHP version (e.g., PHP 7.4) even when project is running on PHP 8.2. This happens because the binary uses a shebang (#!/usr/bin/env php) which picks up the system PHP instead of your project's PHP version.
Important: This value:  `./vendor/bin/pint` of `cs_fixer_command ` is published from our default configuration.
#### What it leads to
1. Complexity to get this package setted-up *specially newly installed user (who just a "USER", not understand muchmore in system relate)*


To relsove: users needed extra steps to configure the correct PHP binary
OR: *Causes unexpected errors when system PHP version doesn't meet requirements, so the setup process can not be done.*

#### Solution:
Here just a first think in my mind, and i'm too lazy to create a fork or pull request :D
First, try to read about 20 first line of configurated `cs_fixer_command `. if there is start of php code block. using `PHP_BINARY` magic contant to excute that binary file.

Example of code (i taken this from modified RealoquentManager::runCodeStyleFixer() ):
```
// Check if binary is a PHP script
        $binaryPath =  str_starts_with($this->csFixerCommand, './') ? base_path(trim($this->csFixerCommand, '"\'./')) : $this->csFixerCommand;
        $isPhpScript = false;
        $binaryPath = explode(' ', $binaryPath)[0];
        if (file_exists($binaryPath)) {
            $content = file_get_contents($binaryPath, false, null, 0, 1000);
            $isPhpScript = str_contains($content, '<?php') ||
                str_contains($content, '#!') && str_contains($content, 'php');
        }

        // Prepare command with PHP_BINARY if needed
        $command = $isPhpScript
            ? PHP_BINARY . ' ' . $this->csFixerCommand
            : $this->csFixerCommand;
